[package]
name = "moving_mammoths"
version = "1.0.0"
authors = []

[addresses]
moving_mammoths = "0xe69c0875d4e04984cfc02b661d2d61fd12a2835347703b0a21efefab40fd2198"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
